FROM node:23.11.1-alpine3.21
WORKDIR '/usr/app'
COPY ./package.json ./
RUN npm config set unsafe-perm true
RUN npm install
COPY . .
RUN chown -R node:node /usr/app/node_modules
CMD ["npm", "run", "start"]
